version: '3'

services:
  web:
    container_name: web
    build: 
      context: .
    image: medods:latest
    environment:
      - DATABASE_URL=postgres://santaasus:youShouldChangeThisPassword@db:5432/test_db?sslmode=disable
    ports:
      - '8080:8080'
    restart: on-failure
    networks:
      - network
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    platform: linux/arm64
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: 'test_db'
      POSTGRES_USER: 'santaasus'
      POSTGRES_PASSWORD: 'youShouldChangeThisPassword'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - ./docker/scripts/scheme.sql:/docker-entrypoint-initdb.d/setup.sql
      - pgdata:/var/lib/postgresql/data
    networks:
      - network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U santaasus -d test_db"]
      interval: 10s
      timeout: 10s
      retries: 10

volumes:
  pgdata:

networks:
  network:
    driver: bridge